# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd95d7cc4d1ded2bcb6159fe33a372683b29be1ec61d408591f6bb595df63a70cce3550eeca04b4bbdc8feeaa2888e5f204df701dcc96898925718de5afa864a

test:
  secret_key_base: f01d3575b78b29316a00e61efdbd9a3b6b7edb20c571d7e8a96d909545e6aff5c4e8e5356110cf0edd99a22bb69040fcd918f747251edc17849bac51eff6a18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
